### ISSUE TITLE
Exported icons not the correct size

### ISSUE THREAD

**Issue by Hekera** [CyclopsMC/IconExporter#11]
Version: 1.2.1 on 1.16.4
I'm trying to export icons of 32x32 size, but when I type /iconexporter export 32, the resulting icons are 80x80. When I try 16, the icons are 40x40. With 2, they're 5x5. The pattern seems to be scale*2.5 = final dimensions, which would mean that I'd need a scale of 12.8 to get 32x32 icons. Because the command only accepts integral values, I attempted the command with 13, but the resulting folder was labelled "12x" and produced 30x30 icons.

**Comment by rubensworks** [comment]
Sounds similar to #7. Are you using Windows?
If so, going to full-screen may fix your problem.
If not, any help on fixing this is welcome, as I don't use Windows myself.

**Comment by Hekera** [comment]
I am on Windows 10. I just tested it in fullscreen, and the problem persists, but now the icons are cut off as described in issue #7.  I have noticed that changing the display resolution in Windows affects the size - I will do more testing shortly. What resolution monitor are you using currently?

**Comment by Hekera** [comment]
I managed to get it """working""" with my 1440p monitor by setting my Windows resolution to 1080p with 150% scale, and not fullscreening Minecraft. The result was double the resolution in the command, so because I wanted 32x32 icons, the command that worked was /iconexporter export 16. From my limited testing, I can't seem to find a coherent pattern. 1440p always seems to generate 80x80 icons, regardless of % scale, but 1080p is definitely affected by % scale.  Fullscreening seems to consistently make icons cut off, but I think that with the right settings (where 32 in the command generates 32x32 icons) this "issue" will no longer exist.

**Comment by rubensworks** [comment]
So it sounds like this is the same problem as #7. Closing this in favor of that one.
