### ISSUE TITLE
java.lang.IllegalStateException: Image is not allocated

### ISSUE THREAD

**Issue by Tethik** [CyclopsMC/IconExporter#12]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When trying to run an export of my own custom modpack, it crashes somewhere halfway through all the items with the above exception. Crashlog will provide more detail.

#### Steps to reproduce the problem:

1. Ingame I run the command `/iconexporter export 128`.

filenameHash and different size 64 did not seem to matter. I checked disk space, which is not an issue. 

I tried disabling the mod that it seemed to crash on (MrCrayfish's Furniture Mod, furniture-7.0.0-pre20-1.16.3.jar), however the crash appeared even with that mod disabled. Could be that I have multiple mods being buggy. 

#### Expected behaviour:

Ideally it would render the item in question without issue. 

Alternatively, when a single item fails to render, it should catch the exception and continue on with the rest of the items. 

____

#### Versions:

- This mod: 1.2.2
- Minecraft: 1.16.5
- Forge: 36.1.18

#### Log file:

https://gist.github.com/Tethik/922db13d79b32a141465c4a279514a6e

Thanks for your useful mod <3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Tethik** [comment]
For my own use-case I'll try to compile a version that just skips on any exception. I'll see if I can narrow down the specific mod(s) causing the issue as well.

**Comment by rubensworks** [comment]
The only way this error can happen if a memory allocation failed, which seems to indicate that your Java VM is running out of memory. Could you try assigning more RAM?

**Comment by Tethik** [comment]
Makes sense. In that case skipping certain mods/items wouldn't make a difference. I bumped up the RAM from ~4GB to ~10GB, which is about as high as it can go on my machine, but the issue still appears. Seems like a memory leak?

**Comment by rubensworks** [comment]
> Seems like a memory leak?

Hmm, that sounds plausible.
