### ISSUE TITLE
BUG: IT DOES NOTHING WHEN I DO THE EXPORT COMMAND!

### ISSUE THREAD

**Issue by PorkingGit** [CyclopsMC/IconExporter#16]
#### Issue type:

- :bug: Bug IT DOESNT CREATE THE EXPORTED ICONS WHEN I DO THE EXPORT COMMAND, (I CHECKED INSIDE MY .MINECRAFT FOLDER AFTER IT SAID THAT ITS DONE EXPORTING)

____

#### Short description:

ITS THE SAME AS THE TITLE!

#### Steps to reproduce the problem:

JUST RUN THE EXPORT COMMAND OKAY?!?!!!

1. ...

#### Expected behaviour:

TO MAKE THE DAMN ICONS LIKE THE MOD SAID IT WOULD

____

#### Versions:

LATEST OKAY, STOP BEING SO NEEDY

**Comment by rubensworks** [comment]
Thanks for reporting!
