### ISSUE TITLE
Image not allocated

### ISSUE THREAD

**Issue by BlackHoleTON618** [CyclopsMC/IconExporter#17]
#### Issue type: Quitting game with crash

- :bug: Bug 
____

#### Short description:

No matter which modpack or version i use it always ends up with quitting the game with a crash.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: [IconExporter-1.16.5-1.2.3.jar
- Minecraft: 1.16.5
- Forge: 36.2.22

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can you try increasing memory?

Similar to #12

**Comment by BlackHoleTON618** [comment]
I gave 10 gb of ram it is not about memory i guess

**Comment by rubensworks** [comment]
@BlackHoleTON618 Could you post the crashlog again? The one posted seems to have been expired.

**Comment by rubensworks** [comment]
The only reason this could be happening AFAICS is if your system is unable to allocate more ram.
I assume you'll be having the same problem when creating regular screenshots via MC (F2/F12).

**Comment by BlackHoleTON618** [comment]
https://crashy.net/1Pj1tN6pIVC9YRzxY3C8

<blockquote><div><strong><a href="https://crashy.net/1Pj1tN6pIVC9YRzxY3C8">Crashy</a></strong></div><div>Formatted Minecraft crash reports</div></blockquote>

**Comment by rubensworks** [comment]
@BlackHoleTON618 What about taking regular screenshots? Do those work?

Does the crash happen from the very first icon? Or just after a while?

**Comment by BlackHoleTON618** [comment]
i can't take screenshot it just shows my pause screen

**Comment by rubensworks** [comment]
If you can't take screenshots in Vanilla MC, then I suspect something is wrong with your system. There's not much I can do to fix your problem then unfortunately.

**Comment by BlackHoleTON618** [comment]
I can take in vanilla mc but not  in modded
