### ISSUE TITLE
A few issue with IconExporter 1.2.0 (MC 1.12.2)

### ISSUE THREAD

**Issue by anhletrung20** [CyclopsMC/IconExporter#18]
#### Issue type:

- :bug: Bug 

____

#### Short description:  A few issue with IconExporter 1.2.0 (MC 1.12.2)
- Rendered Stained Glass is dark
![image](https://user-images.githubusercontent.com/79193776/158056689-0fc19395-6529-4553-8c2a-5c1cb3f50656.png)

- Some fluid when rendered has incorrect color
For example: In-game fluid: Molten Glass (Tinkers' Construct)
![image](https://user-images.githubusercontent.com/79193776/158056606-ba908caa-8bcd-41cc-a743-85051e009034.png)
Rendered Fluid:
![image](https://user-images.githubusercontent.com/79193776/158056643-d369f137-5207-4337-b02e-aac150339d81.png)
Note that other fluids are rendered just fine.
Others incorrect color fluids include Molten Silver and Molten Tin (although you may need to get Thermal Foundation or Mekanism to see it)

#### Steps to reproduce the problem:

1. Install IconExporter and another mod (in this case Tinkers' Construct)
2. Open a world and use export command (I used `/iconexporter export 128`)

#### Expected behaviour: Image of the items exported is the same as shown in-game.

____

#### Versions:

- This mod: 1.2.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but the 1.12 version is not supported anymore. This should be fixed in the 1.16 and 1.18 versions though. (please let me know if this wouldn't be the case)
