### ISSUE TITLE
Dark transparent items

### ISSUE THREAD

**Issue by anhletrung20** [CyclopsMC/IconExporter#20]
#### Issue type:

- :bug: Bug 

____

#### Short description: Dark transparent items

Follow up on the issue I encountered using IconExporter 1.2.0 for MC 1.12.2, I got the same issue when I use dthe latest version of the mod for MC 1.19
Some items such as Stained Glass, Ice or Honey when rendered appear to have a black background
![image](https://user-images.githubusercontent.com/79193776/177174253-08627c48-b2d9-42da-9933-dbadd478b520.png)
Here are some transparent items affected by this issue and some that are not.

#### Steps to reproduce the problem:

1. Install IconExporter
2. Open a world and use export command (I used `/iconexporter export 64`)

#### Expected behaviour: Image of the items exported is the same as shown in-game.

____

#### Versions:

- This mod: 1.2.3
- Minecraft: 1.19
- Forge: 41.0.63

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Fixed in the 1.18 version. The 1.19 will come soon (Forge went through some breaking changes...).
