### ISSUE TITLE
Player Head 

### ISSUE THREAD

**Issue by scorninpc** [CyclopsMC/IconExporter#22]
#### Issue type:

- :question: Question 

____

#### Question:

There is a way to get png icon from player head? i've about 200 players to get they head icons, but i dont know how can i do this. If i create the head, when i export, this mod will get this "item"? or only vanila default itens?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
This mod will only create icons from items in the creative tabs. If you can get them in there somehow, you should get their icons.

An alternative would be to create an extension of this mod.
