### ISSUE TITLE
Memory Leak :sweat_drops: 

### ISSUE THREAD

**Issue by pietro-lopes** [CyclopsMC/IconExporter#23]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. export icons :nerd_face: 
2. watch memory go zoom :chart_with_upwards_trend: 
3. pc goes boom :boom: 

#### Expected behaviour:

____

#### Versions:

- This mod: IconExporter
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
No log, only :boom:  before log

![image](https://github.com/CyclopsMC/IconExporter/assets/97140255/88829d8e-cfaa-4918-983c-60b1fd379519)
(I closed MC before it crashes my PC again)

**Comment by rubensworks** [comment]
Thanks for reporting!
