### ISSUE TITLE
Failure to export items with slashes in key

### ISSUE THREAD

**Issue by iTrooz** [CyclopsMC/IconExporter#26]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Items with slashes in their key don't export, such as spawn eggs in Occultism (ATM9 modpack)

#### Steps to reproduce the problem:

- install a mod with such items (for example Occultism in the ATM9 modpack)
#### Expected behaviour:

It should export the texture

____

#### Versions:

- This mod: 1.2.5
- Minecraft: 1.20.1
- Forge: 47.2.20
- OS: Linux

#### Log file:

Relevant error: https://pastebin.com/74r2kWt3

#### More info

I think the correct course of action would be to replace slashes by `___` (to avoid confusion with other separators) at https://github.com/CyclopsMC/IconExporter/blob/b95d3c91f2498309262a541948fbbecadc1df0a9/src/main/java/org/cyclops/iconexporter/client/gui/ScreenIconExporter.java#L112, or create the required directory automatically
I'd be ready to submit a PR for this, let me know what you think

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> think the correct course of action would be to replace slashes by ___ (to avoid confusion with other separators)

Sounds like a good solution indeed!
