### ISSUE TITLE
Log errored export task instead of stop the whole exporting process

### ISSUE THREAD

**Issue by TowardtheStars** [CyclopsMC/IconExporter#4]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Sometimes this mod will encounter items that cannot be exported properly. And when it happens, the mod simply stops the whole exporting process and show a message:"Error while exporting". This is annoying when users have a lot of items from hundreds of mods to export.

So, could you please remove the feature that will stop the process when encountering a small error? Maybe by replacing with a log or something alike that reports items are going wrong? 

Pretty please?

**Comment by TowardtheStars** [comment]
Emmm... If you don't want to remove that feature, would you please add a config for it?

**Comment by rubensworks** [comment]
Sure, that would indeed be a more user-friendly way to go.
