### ISSUE TITLE
Record NBT tags of items in text files instead of in file names

### ISSUE THREAD

**Issue by TowardtheStars** [CyclopsMC/IconExporter#5]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Would you please use text files to record NBT tags of items instead of printing them on file names?

Since some OS and FS put a limit on the length of file name, it seems not convenient to simply export long NBT tags in file names. So such a long file name may raise an IOException when writing files. 

The situation described above is possible when the user is working with mods such as TinkersConstruct, whose items always contain long NBT tags. A NBT tag of a tool from TinkersConstruct can easily reach 300 or more ASCII characters, and it will always get involved in task list when the user tries to export. It would get worse if the user installed some addons for TinkersContruct such as TAIGA and plusTiC.

**Comment by rubensworks** [comment]
Note to self: apply a deterministic hash of the NBT tag to use in the file name, and store the full tag contents in a meta file.
