### ISSUE TITLE
Maybe export locallized names of items along with their icons?

### ISSUE THREAD

**Issue by TowardtheStars** [CyclopsMC/IconExporter#6]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Would you please add a feature that can export locallized names of items along with icons and NBT tags?

Sometimes users might need locallized names of items. For example, when ops want to make a shopping list for a server with economy system, it would be convenient to have locallized names exported along with icons and NBT tags, both for ops and other players.

Pretty please?

**Comment by rubensworks** [comment]
This feels a bit out-of-scope for the goal of this mod, but I understand it could be useful.

I'm just leaving this open in case I change my mind, but I'm giving it a lower priority.

**Comment by Krutoy242** [comment]
+1 for this feature!

**Comment by iTrooz** [comment]
Hey ! I'd need this feature too, and I'm ready to submit a PR for it

I'd make a  `exportlocalnames` subcommand that creates a JSON file that maps the files paths to the localised names.

What do you think about this feature ? Would you accept a PR for it ?
Looking forward to your feedback

**Comment by rubensworks** [comment]
> I'd make a exportlocalnames subcommand that creates a JSON file that maps the files paths to the localised names.

@iTrooz Sure, that sounds reasonable. A PR is definitely welcome!
