### ISSUE TITLE
[1.14.4] Game crashes when execute "iconexporter export" command

### ISSUE THREAD

**Issue by theogiraudet** [CyclopsMC/IconExporter#8]
#### Issue type:

- :bug: Bug

____

#### Short description:

The bug appears when the mod render enchanted book. The game crashes and stop.

#### Steps to reproduce the problem:

Command /iconexporter export.
____

#### Versions:

- This mod: 1.14-1.2.0
- Minecraft: 1.14.4
- Forge: 1.14.4-28.1.109

#### Log file:

https://pastebin.com/eYrsYg5S

**Comment by rubensworks** [comment]
Looks like a Windows-specific bug, thanks for reporting.

**Comment by rubensworks** [comment]
Should be fixed in the next update. Feel free to try out the latest dev build in the meantime.
